### ISSUE TITLE
Remove toilet and libcaca.

### ISSUE THREAD

**Issue by kori** [6c37/crux-ports#3]
z3bra already maintains these ports:

http://git.z3bra.org/cgit.cgi/crux/tree/toilet/Pkgfile
http://git.z3bra.org/cgit.cgi/crux/tree/libcaca/Pkgfile

**Comment by JSchilli1** [comment]
z3bra's port installs man pages to /usr/share/man (instead of /usr/man), is version 0.99.beta18 (instead of the latest, beta19), doesn't include dependencies, and isn't in our repo! personally, i think having multiple ports of the same package is a good thing, it gives users freedom of choice. there are also multiple ports available for the same software package on crux.nu user repos, i don't see the problem.

**Comment by kyubiko** [comment]
Personally I think out is better to include as many ports as we can, even if they are duplicates. It is far nicer to add one repo and be able to install a bunch of packages, instead of ending up with a system with lots of repos added each one only with a few actually installed packages in.

**Comment by kori** [comment]
Good points.
Well, I also think we can maintain these.
We have more contributors so it's easier to point out if updates are needed.
