### ISSUE TITLE
remove compton?

### ISSUE THREAD

**Issue by maraku** [6c37/crux-ports#77]
I was thinking that maybe it would be best if compton was removed? The last 'stable' (actually a beta) release was in 2013, and it doesn't compile because of some asciidoc problems. The git version works, but disables `make docs` (because of asciidoc problems).

**Comment by kori** [comment]
If the git version is kept, that's fine by me.

**Comment by rtlanceroad** [comment]
@maraku  It's builds fine here. The reason I added it to here is because I didn't enable -git repo(because git means you are on upstream development stage and not for production) but I did need a compositor. Since 2013, the upstream has pushed a lot of commits and they should have released a stable tarball if this makes sense to you.

**Comment by maraku** [comment]
yeah, thanks for the explanation @rtlanceroad, i guess stability vs. new features then? also, i think the problem with asciidoc is on my side because dbus also fails to compile due to xml validation errors.

**Comment by rtlanceroad** [comment]
@maraku you need to either add `--install-scripts` when you run `prt-get depinst docbook-xml docbook-xsl` or enable ` runscripts yes` in /etc/prt-get.conf. Hopefully this will help.

**Comment by rtlanceroad** [comment]
I'll close it :)
