### ISSUE TITLE
kicad tweaks

### ISSUE THREAD

**Issue by rmull** [6c37/crux-ports#78]
Seeing as there is at least one other kicad user here (@rtlanceroad) here, I'd like to verify that a change to the Pkgfile I'm considering is acceptable:

`-DBUILD_GITHUB_PLUGIN=OFF`

The github plugin fails to build when using libressl instead of openssl. The advantage of the github plugin (as far as I understand it) is so that kicad users can keep their footprint libraries up-to-date automatically based on the community-managed github-based libraries. However, it also means that your design might change without your intention, and there is nothing stopping the user from doing a one-time manual sync with the github libs anyway.

I would like to turn the github plugin off in order to support building with libressl and to support a more standalone development mode. The alternative would be to patch the kicad code in order to make it support both libressl and openssl, but since I don't use the github plugin, it would be easier just to disable it...

Thoughts?

**Comment by rtlanceroad** [comment]
Agreed. Feel free to do what you think @rmull ! :)
I've checked related infomation you mentioned before and [github hosted mirror](https://github.com/KiCad/kicad-source-mirror), they have following lines from CMakeList.txt in main directory:
```
#
# Find CURL library, required for github plugin
#
if( BUILD_GITHUB_PLUGIN )
    find_package( CURL REQUIRED )
endif()
```
and following lines from pcbnew/CMakeLists.txt in sundirectory:
```
if( BUILD_GITHUB_PLUGIN )
    set( GITHUB_3DLIBRARIES_WIZARD
            dialogs/wizard_3DShape_Libs_downloader_base.cpp
            dialogs/wizard_3DShape_Libs_downloader.cpp )
endif()
```
the two c++ files will use curl to get the 3DShape libs from a lot of headers as I can see:
```
#define DEFAULT_GITHUB_3DSHAPES_LIBS_URL \
    wxT( "https://github.com/KiCad/kicad-library/tree/master/modules/packages3d" )
```
so above things are just materials to approve you are right. I dont have have libressl installed since it's a openssl fork and I think it will break my crux setup. But disable github plugins for pcbnew is harmless from any perspective. :)

**Comment by rmull** [comment]
@rtlanceroad - I made some changes to the Pkgfile, see commit 1486b314dab062a62ffdd6ddc1fcce5fd75ce2dc and make sure all is well. If it looks okay, please feel free to close this issue.

**Comment by rtlanceroad** [comment]
Looks good to me, closing.
