### ISSUE TITLE
CRUX 3.2 prt-get "cyclic dependencies" problem

### ISSUE THREAD

**Issue by dlcusa** [6c37/crux-ports#86]
I last ran CRUX 3.2 ports -u on Jan 23.  Today after ports -u, prt-get reports "cyclic dependencies". I analyzed the diffs and came up with the following Depends On changes and port deletions/additions:

 ```
1)                     6c37 android-tools       dropped git
 2) new pkg              opt autoconf-archive    has no deps
 3)              deepthought conky               added libircclient
 4) dropped prt          opt libsexy             xfce port now top dog (both depon gtk)
 5)                      opt hexchat             dropped libsexy, added autoconf-archive
 6) new pkg      deepthought libircclient        has openssl
 7) new pkg             6c37 neomutt             has no deps
 8)                  dbrooke numpy               dropped python, added setuptools
 9)                     6c37 python3-setuptools  dropped python3, added python3-pip
10) new pkg              df sgrmm               has deps pmount and pygtk
11) dropped pkg        6c37 the_silver_searcher had no deps
12)                 contrib wxgtk               dropped gst-plugins-base-compat, added gst-plugins-base
```

Assuming I did my homework correctly, hopefully at least one of you maintainers will see the problem.

**Comment by dlcusa** [comment]
That sure didn't format well.  Got an email address I can use like for the other maintainers?

**Comment by rtlanceroad** [comment]
Thanks for reporting, but I still don't get the point about what your saying, the graph looks messy for me. 

>  Today after ports -u, prt-get reports "cyclic dependencies". 

cyclic dependencies between/among what packages?

Things need to get clear :)

**Comment by dlcusa** [comment]
Well, prt-get's "cyclic dependencies" difficulties have been around for over a decade, but that hasn't motivated its maintainers to enhance it to be more clear about where the circular dependencies exist.  Instead, the approach seems to be find out which packages were added, deleted, or otherwise had their Depends On definitions changed to produce the situation.  I've provided that information to the maintainers of that set.  You're supposed to know how to evaluate your changes in light of prt-get's displeasure.  I think romster is the most likely maintainer to need to do something, but he's been extremely busy and has to prioritize his support efforts--it may be a while before he weighs in.

**Comment by dlcusa** [comment]
```
On 17Jan27:1037+0000, David Brooke wrote:
>
> Maybe you could try to disable my repository to see if that helps?

Sure, probably later this morning.  And if that doesn't make prt-get
happy, I'll do the same thing with the other collections one-by-one
until the culprit is made plain.  BTW, another ports -u has not
changed the situation (wasn't expecting it to, of course).  
```

**Comment by dlcusa** [comment]
```
Just replied to David Brooke with copies to the other maintainers:
Removing collection dbrooke from the mix did not make prt-get happy,
so you're off the hook.  Thanks for the idea--I should have thought
of that approach myself.
```

**Comment by dlcusa** [comment]
```
Since I have no deepthought ports installed, I tried that collection
next with the same result, so now Erich's off the hook, too.  That
leaves Danny and the 6c37 crew.  Now it becomes more difficult (the
/var/lib/pkg/prtpkg_by_pkg.*.log file shows all the ports / packages
currently installed and/or built on my system):

# head -1 /var/lib/pkg/prtpkg_by_pkg.20170127-043129.log \
> egrep 'android\-tools|autoconf\-archive|conky|libsexy|hexchat|libircclient|neomutt|numpy|python3\-setuptools|sgrmm|the_silver_searcher|wkgtk' \
> /var/lib/pkg/prtpkg_by_pkg.20170127-043129.log
package----------- pkg/db_version- port_version collection-- date_time----------
           hexchat 2.12.4-1        [same]       opt          20161216-23:04:15UT
           libsexy 0.1.11-2        [same]       opt          20170113-17:22:29UT
             numpy 1.11.2-1        [same]       df           20170113-11:33:43UT
python3-setuptools 32.3.1-1        [same]       6c37         20170113-11:11:40UT

*light bulb turns on*

What if prt-get sysup is only checking installed packages for "cyclic
dependencies"?  If so, I'm wondering now if the problem is in prt-get
having to deal with an installed package whose port has been deleted
(opt/libsexy).
```
So I sent this to the Maintainer of crux/prt-get (CRUX Support Team, <core-ports@crux.nu>) with suitable back story...

**Comment by rtlanceroad** [comment]
While I thought I got part of your saying. `cyclic dependencies` seems _unavoidable_ because of several reasons:

-  From [crux homepage](https://crux.nu/), you see ` The primary focus of this distribution is keep it simple, which is reflected in a straightforward tar.gz-based package system, BSD-style initscripts, and a relatively _small collection_ of trimmed packages.` so it means we developers only focus on packages that are _critical_ to the system, and we developers hope users to use official repo only, and use your repo with cautions and other repo with self-repobosibility. Third party repo may break the system. For me, when I first used crux, I use the following repo:  `core` `opt` `xorg` `contrib` `6c37 ``myrepo`, but I saw the possibility that 6c37 could give me better maintaince, so I joined the team and merged my repo to 6c37. Today I only use one third-party repo---`6c37`. 

- If you use our repo, you will find there are _some same package, with/without version_. So why we do this fork thing? Some of them are out-of-date paackages that maintainers wouldn't give update for them or those ones are orphaned, others are wrongly built with wrong flags, like man page location(3.1 installs man pages to /usr/man/, and 3.2 changed to /usr/share/man/ but some maintainers forgot to change this,)

- Some other third party repo _may_ have special use, so they may be used in special circumstance. Like a electronic technician may focus packages which give better views for electonics, so they may choose kicad from our repo, or use it from dbrooke repo, so it depends.

I rely this when I half drunk. I drunk a lot of wine today, the first day of spring festival. Hopefully I expressed them clearly.  :)

**Comment by rtlanceroad** [comment]
I tested packages in Virtualbox with fresh install today and found `cyclic dependencies` between `python3-setuptools` and `python3-pip` when using prt-get. I followed README under package `python3-pip` and it broke `cyclic dependencies` for me. How about you?

**Comment by dlcusa** [comment]
I can't find any README:
```
# /bin/ls -lah /usr/ports/*/python3-pip
/usr/ports/kris/python3-pip:
total 72K
drwxr-xr-x  2 root root 4.0K Aug 22 17:33 .
drwxr-xr-x 74 root root 4.0K Jan 29 05:04 ..
-rw-r--r--  1 root root  54K Feb 29  2016 .footprint
-rw-r--r--  1 root root   51 Feb 29  2016 .md5sum
-rw-r--r--  1 root root  457 Feb 29  2016 Pkgfile

/usr/ports/t0b1nux/python3-pip:
total 72K
drwxr-xr-x  2 root root 4.0K Sep 16 19:14 .
drwxr-xr-x 43 root root 4.0K Jan 29 05:05 ..
-rw-r--r--  1 root root  56K Sep 16 18:55 .footprint
-rw-r--r--  1 root root   51 Sep 16 18:55 .md5sum
-rw-r--r--  1 root root  457 Sep 16 18:55 Pkgfile
# /bin/ls -lah /usr/ports/6c37/python3-setuptools
total 24K
drwxr-xr-x   2 root root 4.0K Jan 26 16:53 .
drwxr-xr-x 236 root root  12K Jan 29 05:02 ..
-rw-r--r--   1 root root   56 Jan 29 05:02 .md5sum
-rw-r--r--   1 root root  579 Jan 29 05:02 Pkgfile
```

Are you talking about a `README` installed for `python3-pip`?  I can't find one in the `.footprint` for any of these ports.

Thanks for connecting this to #85--now we're getting somewhere.

**Comment by rtlanceroad** [comment]
which way are you using to sync 6c37? httpup or git? No matter what you use, just sync repo right now, and you'll find them.

**Comment by dlcusa** [comment]
I synced a couple hours ago (?).

**Comment by rtlanceroad** [comment]
The changes were not pushed when you synced it.

**Comment by dlcusa** [comment]
I never saw the readme--I just ran my portsu script that includes a "prt-cache sysup --test" command that completed nominally.

**Comment by rtlanceroad** [comment]
`python3-pip` README: https://github.com/6c37/crux-ports/blob/3.2/python3-pip/README
`python3-setuptools` README: https://github.com/6c37/crux-ports/blob/3.2/python3-setuptools/README
they should be in ports.

Now everything should be good to go.
