### ISSUE TITLE
Signature mismatch found

### ISSUE THREAD

**Issue by lounqe** [6c37/crux-ports#90]
Hi ,
Just to let you know
I got lots of signature mismatch error found in 6c37 and 6c37-git repos like mpv,mpd,dunst,libxdg-basedir etc

**Comment by onodera-punpun** [comment]
Hmm I do get signature mismatches for mpv, mpd and duns (all 6c37-git ports), but libxdg-basedir works just fine.

I think it has something to do with sourceless Pkgfiles, probably a bug with pkgmk....

**Comment by rtlanceroad** [comment]
@lounqe Hi, I agreed with @onodera-punpun . Packages in 6c37 repo won't get signature mismatch because they are fixed release. But packages in 6c37-git will cause it because fast development, like new features added in or old features dropped out, will produce a different `.footprint` therefore a different signature.  As I can suggest, you can pass `-is` to pass signature check if you have signature issue in 6c37-git repo.

**Comment by rtlanceroad** [comment]
I'll close it now.
